#!/usr/bin/env bash
#---------------------------------------
# Autor    : guilherme
# Script   : case
# Data     : 04/08/23
# Versao   : Brasileira :)
# Licenca  : EAD
# Descricao: testando-case 
#---------------------------------------
# Uso: Fins educativos
#---------------------------------------
clear

#case VALOR in
#	PADRAO) BLOCO DE COMANDOS ;;
#	PADRAO) BLOCO DE COMANDOS ;;
#	PADRAO) BLOCO DE COMANDOS ;;


case ${1,,} in
	banana|abacaxi) echo "$1 eh amarela" 				;;
	abacate|uva|limao) echo "$1 eh verde" 				;;
	morango|maca|tomate|pitanga) echo "$1 eh vermelha" 		;;
	     *) echo "Nao sei a cor de $1" 				;;
esac

exit 0
