#!/usr/bin/env bash


echo $1



#pede o nome do app pro user
#read -p "Qual programa deseja instalar? " package

#atualiza oque tem que atualizar
flatpak update



#instala o programa digitado
flatpak install $1


