#!/usr/bin/env bash
#---------------------------------------
# Autor    : guilherme
# Script   : arrayindexadas
# Data     : 28/07/23
# Versao   : Brasileira :)
# Licenca  : EAD
# Descricao: 
#---------------------------------------
# Uso: Fins educativos
#---------------------------------------

clear

echo "\
Exemplo de arrays indexadas...
"
read -p "Digite um numero entre 0 e 5: " numero

frutas=("banana" "laranja" "abacate" "limao" "cereja" "abacaxi")
cores=("amarela" "laranja" "verde" "verde" "vermelha" "amarela")

[[ ! $numero =~ ^[0-5]$ ]] \
	&& echo -e "\nTem que ser um numero entre 0 e 5! Saindo...\n" \
	&& exit 1

echo "Voce escolheu ${frutas[$numero]}, que e uma fruta ${cores[$numero]}."

exit 0
