#!/usr/bin/env bash
#---------------------------------------
# Autor    : guilherme
# Script   : checapid
# Data     : 27/07/23
# Versao   : Brasileira :)
# Licenca  : EAD
#---------------------------------------
# Uso: /caminho/checapid ou ./checapid
#---------------------------------------

clear

sep="========================================================="


echo "$sep
COMPARANDO PID DAS SESSOES DO BASH NO SCRIPT E NO TERMINAL
$sep
PID da sessao do bash do script: $$
PID da sessao do bash no terminal: $PPID
$sep
$(ps -p $$,$PPID -o pid=,user=,tty=,args=)
$sep
"

exit 0
